import type { Pet } from '@/types'

export const PETS: Pet[] = [
  { id:1,  name:'Buddy',    type:'Dog',     breed:'Golden Retriever',   age:'2 years',  gender:'Male',   weight:'28.5 kg', location:'Semarang', status:'Available',  vaccinated:true,  neutered:false, img:'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80', desc:'Buddy is a friendly and energetic Golden Retriever who loves to play fetch and go on walks. He is great with kids and easy to train.' },
  { id:2,  name:'Luna',     type:'Cat',     breed:'Persian',            age:'3 years',  gender:'Female', weight:'4.2 kg',  location:'Semarang', status:'Available',  vaccinated:true,  neutered:true,  img:'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&q=80', desc:'Luna is a calm and affectionate Persian cat who loves being brushed and sitting in laps. Perfect for a quiet home.' },
  { id:3,  name:'Rio',      type:'Bird',    breed:'Cockatiel',          age:'1 year',   gender:'Male',   weight:'0.1 kg',  location:'Semarang', status:'Available',  vaccinated:false, neutered:false, img:'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=600&q=80', desc:'Rio is a cheerful cockatiel who loves to sing. He is easy to tame and enjoys interacting with people.' },
  { id:4,  name:'Daisy',    type:'Dog',     breed:'Beagle',             age:'1 year',   gender:'Female', weight:'10.3 kg', location:'Semarang', status:'Available',  vaccinated:true,  neutered:false, img:'https://images.unsplash.com/photo-1537204696486-967f1b7198c8?w=600&q=80', desc:'Daisy is a curious and playful Beagle. She loves outdoor activities and exploring new places.' },
  { id:5,  name:'Milo',     type:'Cat',     breed:'Domestic Shorthair', age:'4 months', gender:'Male',   weight:'1.8 kg',  location:'Semarang', status:'Available',  vaccinated:false, neutered:false, img:'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&q=80', desc:'Milo is a high-energy kitten full of curiosity. He loves playing with toys and exploring every corner.' },
  { id:6,  name:'Draco',    type:'Reptile', breed:'Bearded Dragon',     age:'2 years',  gender:'Male',   weight:'0.45 kg', location:'Semarang', status:'Available',  vaccinated:false, neutered:false, img:'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&q=80', desc:'Draco is a gentle bearded dragon who enjoys basking and being handled. Great for first-time exotic pet owners.' },
  { id:7,  name:'Coco',     type:'Bird',    breed:'Lovebird',           age:'8 months', gender:'Female', weight:'0.06 kg', location:'Semarang', status:'Available',  vaccinated:false, neutered:false, img:'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&q=80', desc:'Coco is a vibrant lovebird with beautiful plumage. She is active and will be a joyful addition to your home.' },
  { id:8,  name:'Rex',      type:'Dog',     breed:'German Shepherd',    age:'3 years',  gender:'Male',   weight:'35 kg',   location:'Semarang', status:'Adopted',    vaccinated:true,  neutered:false, img:'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&q=80', desc:'Rex is a loyal and intelligent German Shepherd. He is protective, trainable, and great for families.' },
  { id:9,  name:'Whiskers', type:'Cat',     breed:'Maine Coon',         age:'2 years',  gender:'Male',   weight:'6.5 kg',  location:'Semarang', status:'Available',  vaccinated:true,  neutered:true,  img:'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&q=80', desc:'Whiskers is a fluffy Maine Coon who gets along with other pets. He even enjoys playing with water!' },
]
